/**
 * A task extracted from a markdown file.
 * Tasks are lines beginning with `- [ ]` (incomplete) or `- [x]` (complete).
 */
export interface Task {
  /** The full text of the task (excluding the checkbox) */
  text: string;
  /** The section this task appears in (e.g., "Focus today", "Quick wins") */
  section: string;
  /** Whether the task is complete */
  complete: boolean;
  /** Jira ID if present (e.g., "DATA-1856") */
  jiraId: string | null;
}

/**
 * An action item extracted from a meeting note's "## Action items" section.
 */
export interface ActionItem {
  /** The full text of the action item */
  text: string;
  /** Jira ID if present */
  jiraId: string | null;
}

/**
 * A daily agenda file from the vault.
 */
export interface DailyAgenda {
  /** The date in YYYY-MM-DD format */
  date: string;
  /** The raw markdown content of the file */
  content: string;
  /** Tasks extracted from the file */
  tasks: Task[];
}

/**
 * A meeting note file from the vault.
 */
export interface MeetingNote {
  /** The date in YYYY-MM-DD format */
  date: string;
  /** The meeting title (from filename) */
  title: string;
  /** Path to the file relative to vault root */
  filepath: string;
  /** File modification timestamp */
  modifiedAt: Date;
  /** Whether the file has an "## Action items" section */
  hasActionItemsSection: boolean;
  /** Action items extracted from the section (if exists) */
  actionItems: ActionItem[];
}

/**
 * A meeting that may need user attention before generating the agenda.
 */
export interface MeetingNeedingAttention {
  /** Path to the file relative to vault root */
  filepath: string;
  /** Reason this meeting needs attention */
  reason: string;
}

/**
 * Context gathered from the vault (Step 2 output).
 */
export interface GatheredContext {
  /** Recent daily agendas within the lookback period */
  recentAgendas: DailyAgenda[];
  /** Recent meeting notes within the lookback period */
  recentMeetings: MeetingNote[];
  /** Meetings that may need user attention */
  meetingsNeedingAttention: MeetingNeedingAttention[];
}

/**
 * The draft agenda sections generated by the LLM.
 * Simplified to 3 sections for low-friction daily planning.
 */
export interface DraftAgenda {
  focusToday: string[]; // Max 3 items
  quickWins: string[]; // Biased towards delegation
  later: string[]; // Everything else
}

/**
 * An item flagged by the LLM as needing clarification.
 */
export interface UnclearItem {
  /** The task text */
  task: string;
  /** Source file where the task originated */
  source: string;
  /** Reason the item is unclear */
  reason: string;
  /** Question to ask the user */
  question: string;
}

/**
 * Response from the LLM triage scan (Step 4 output).
 */
export interface LLMTriageResponse {
  /** The draft agenda with categorized tasks */
  draftAgenda: DraftAgenda;
  /** Items that need user clarification */
  unclearItems: UnclearItem[];
  /** Optional suggestions from the LLM */
  suggestions: string[];
}

/**
 * Resolution type for an unclear item.
 */
export type ResolutionType = "done" | "focus_today" | "quick_win" | "later" | "drop";

/**
 * A resolved unclear item after user input (Step 5 output).
 */
export interface ResolvedItem {
  /** The original task text */
  task: string;
  /** How the user resolved this item */
  resolution: ResolutionType;
  /** Additional context provided by user (e.g., delegation target, reason) */
  context: string;
}

/**
 * Valid section names in a daily agenda file.
 */
export type AgendaSection = "Focus today" | "Quick wins" | "Later";

/**
 * Mapping from section names to their descriptions.
 */
export const SECTION_DESCRIPTIONS: Record<AgendaSection, string> = {
  "Focus today": "1-3 things that would make today successful",
  "Quick wins": "Small tasks, delegations, and quick actions",
  Later: "Deferred items to revisit",
};

/**
 * Ordered list of agenda sections.
 */
export const AGENDA_SECTIONS: AgendaSection[] = ["Focus today", "Quick wins", "Later"];

// =============================================================================
// GitHub Integration Types
// =============================================================================

/**
 * A pull request from GitHub.
 */
export interface PullRequest {
  /** PR number */
  number: number;
  /** PR title */
  title: string;
  /** URL to the PR */
  url: string;
  /** Head branch name (e.g., "dank/FSW-1234-fix-thing") */
  branch: string | null;
  /** Jira ID extracted from title (e.g., FSW-1234) */
  jiraId: string | null;
  /** Whether required_hil_checks CI is passing */
  hilChecksPassing: boolean | null;
  /** Whether the PR has an approved review */
  hasApproval: boolean;
  /** Review state: APPROVED, CHANGES_REQUESTED, PENDING, etc. */
  reviewState: string;
  /** PR state: open, closed, merged */
  state: string;
}

// =============================================================================
// Jira Integration Types
// =============================================================================

/**
 * A Jira ticket.
 */
export interface JiraTicket {
  /** Ticket key (e.g., FSW-1234) */
  key: string;
  /** Ticket summary/title */
  summary: string;
  /** Current status (e.g., "In Progress", "In Review") */
  status: string;
  /** URL to the ticket */
  url: string;
  /** Whether this ticket has a linked PR (set by reconciler) */
  hasLinkedPR: boolean;
  /** Linked PR number if any */
  linkedPRNumber: number | null;
}

// =============================================================================
// Reconciliation Types
// =============================================================================

/**
 * A discrepancy between GitHub and Jira state.
 */
export interface ReconciliationWarning {
  /** Type of discrepancy */
  type: "pr_no_ticket" | "ticket_no_pr" | "status_mismatch" | "needs_approval";
  /** Human-readable message */
  message: string;
  /** Related PR number if applicable */
  prNumber?: number;
  /** Related Jira key if applicable */
  jiraKey?: string;
}

/**
 * Result of reconciling GitHub PRs with Jira tickets.
 */
export interface ReconciliationResult {
  /** PRs matched to tickets */
  matchedPRs: PullRequest[];
  /** Tickets matched to PRs */
  matchedTickets: JiraTicket[];
  /** PRs without matching tickets */
  unmatchedPRs: PullRequest[];
  /** Tickets without matching PRs */
  unmatchedTickets: JiraTicket[];
  /** Warnings about discrepancies */
  warnings: ReconciliationWarning[];
}

// =============================================================================
// Enhanced Context Types
// =============================================================================

/**
 * Enhanced context including GitHub and Jira data.
 */
export interface EnhancedContext extends GatheredContext {
  /** Open pull requests */
  pullRequests: PullRequest[];
  /** In-progress and in-review Jira tickets */
  jiraTickets: JiraTicket[];
  /** Reconciliation result */
  reconciliation: ReconciliationResult;
  /** User's input about what they're working on today */
  userFocusInput?: string;
}
